name: weekly-report-bot-test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install
        run: npm install

      - name: run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          FORUM_CHANNEL_ID: ${{ secrets.FORUM_CHANNEL_ID }}
        run: node index.js